#!/bin/bash
echo ""
echo "══════════════════════════════════════════════════════════════"
echo "  🎉 DIET CAFÉ APP - EXPO LINK READY!"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "📱 TO OPEN ON YOUR PHONE:"
echo ""
echo "   1. Install 'Expo Go' app from App Store (iOS) or Play Store (Android)"
echo ""
echo "   2. Open this link in your phone browser:"
echo "      👉 https://dietcafe-app.preview.emergentagent.com"
echo ""
echo "   3. Or scan QR code from Expo Go app camera"
echo ""
echo "══════════════════════════════════════════════════════════════"
echo "  🌐 WEB ADMIN PANEL:"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "   👉 https://dietcafe-app.preview.emergentagent.com"
echo ""
echo "   Login with:"
echo "   • Admin account (if created)"
echo "   • Or create new staff account"
echo ""
echo "══════════════════════════════════════════════════════════════"
echo "  📊 STATUS:"
echo "══════════════════════════════════════════════════════════════"
echo ""
sudo supervisorctl status | grep -E "(backend|frontend|mongodb)"
echo ""
echo "══════════════════════════════════════════════════════════════"
echo ""
